### ISSUE TITLE
Trying hard to find how to install the package

### ISSUE THREAD

**Issue by jony1286** [gregversteeg/NPEET#20]
for some reason the 'setup.py' file only gives this warning:

`runfile('C:/Users/Yonatan/Documents/GitHub/NPEET/setup.py', wdir='C:/Users/Yonatan/Documents/GitHub/NPEET')
Reloaded modules: npeet, npeet.entropy_estimators
An exception has occurred, use %tb to see the full traceback.
Traceback (most recent call last):
  File "C:\Users\Yonatan\anaconda3\lib\distutils\core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "C:\Users\Yonatan\anaconda3\lib\site-packages\setuptools\dist.py", line 707, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "C:\Users\Yonatan\anaconda3\lib\distutils\dist.py", line 501, in parse_command_line
    raise DistutilsArgError("no commands supplied")
DistutilsArgError: no commands supplied
During handling of the above exception, another exception occurred:
SystemExit: usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: no commands supplied`

tried to install from CMD too with no response.
but for some reason not clear to me for the test.py file i can operate the library. 

Help pls! s
![Capture](https://user-images.githubusercontent.com/49495893/85944458-88f42000-b93f-11ea-958f-e8e38df8a431.PNG)
omebody has an explanation?

** the test file for some reason works perfect...

**Comment by jony1286** [comment]
** update! 

To solve the issue I needed to update my pip install and run the build/install in the anaconda environment after!

thanks anyway!
and thank you gregversteeg for sharing your work.
